// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDirRGjocKxcDf-r85l_ZBl29grwkEhMI',
    appId: '1:449899501773:web:3d787cb12db37fc4b03184',
    messagingSenderId: '449899501773',
    projectId: 'baraka-d0159',
    authDomain: 'baraka-d0159.firebaseapp.com',
    storageBucket: 'baraka-d0159.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qiBpSBSn6Kf_NThckf1AB0YBRqDqeXg',
    appId: '1:449899501773:android:c256530f919dc9c5b03184',
    messagingSenderId: '449899501773',
    projectId: 'baraka-d0159',
    storageBucket: 'baraka-d0159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBJ3YhCNs50Lv_e8FFc91DEt6FAdG9Bwo',
    appId: '1:449899501773:ios:ccbcb4e9a6174a55b03184',
    messagingSenderId: '449899501773',
    projectId: 'baraka-d0159',
    storageBucket: 'baraka-d0159.appspot.com',
    iosClientId: '449899501773-hpc7j374i3mq73dnj5ju1cqclgulbhr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.baraka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBJ3YhCNs50Lv_e8FFc91DEt6FAdG9Bwo',
    appId: '1:449899501773:ios:ccbcb4e9a6174a55b03184',
    messagingSenderId: '449899501773',
    projectId: 'baraka-d0159',
    storageBucket: 'baraka-d0159.appspot.com',
    iosClientId: '449899501773-hpc7j374i3mq73dnj5ju1cqclgulbhr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.baraka',
  );
}
